# Copyright (c) 2022 bytes at work AG. All rights reserved.


# Changelog
#
# [1.0.0] - 2022-03-31: Initial version


# This Github action checks a pull request using checkpatch
name: checkpatch
on: pull_request
jobs:
  checkpatch:
    name: Checkpatch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y perl

      - name: Create patch file(s)
        # create patch file(s) of new commits (between base and head)
        run: git format-patch ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} || exit 1

      - name: Run checkpatch
        run: ./scripts/checkpatch.pl *.patch
